name: Build Windows

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg (from cache, no packages yet)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 5b1214315250939257ef5d62ecdcbca18cf4fb1c

      - name: Configure
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
          -DVCPKG_TARGET_TRIPLET=x64-windows-static

      - name: Build
        run: cmake --build build --config Release -- -v

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: hrg_logger-windows
          path: build\hrg_logger.exe
